### ISSUE TITLE
can't upgrade autoResponder  to 3.0.3 because of issue

### ISSUE THREAD

**Issue by klict** [ebizmarts/magento2-autoresponder#3]
when upgrading autoresponder to 3.03 and i get this as result.

> We found conflicting component dependencies. Hide detail
> 
> You are trying to update package(s) ebizmarts/magento2-autoresponder to 3.0.3
> We've detected conflicts with the following packages:
> - ebizmarts/magento2-mandrill version 3.0.4. Please try to update it to one of the following package versions: dev-master, 3.0.3, 3.0.2, 3.0.1, 3.0.0, dev-develop

**Comment by gonzaloebiz** [comment]
Fixed in the Release 3.0.5
