### ISSUE TITLE
Error on cron run

### ISSUE THREAD

**Issue by magarence** [ebizmarts/magento2-autoresponder#4]
Using Magento 2.1, Auto Responder 3.0.6

Mails not sending.

Errors in cron log:
PHP Fatal error:  Class 'Ebizmarts\AutoResponder\Model\Mage' not found in /usr/share/nginx/html/artisanart/test/app/code/Ebizmarts/AutoResponder/Model/Cron.php on line 165
$collection = Mage::getModel('customer/customer')->getCollection();

**Comment by SantiParagarino** [comment]
Hello @magarence 

Solved at https://github.com/ebizmarts/magento2-autoresponder/commit/0efbbd8646a231badb9c444767b9af74d0719b59

I am releasing a new version (3.0.7) right now with this change.
