### ISSUE TITLE
Error when opening autoresponder configuration page

### ISSUE THREAD

**Issue by pitangaweb** [ebizmarts/magento2-autoresponder#5]
**Situation**
On Magento 2.1.0 with MageMonkey 3.0.7 and Autoresponder 3.0.6 installed.
Open "Stores" > "Configuration" > "Magemonkey" > "Autoresponder"

**Problem**
I get the following error:
`Exception #0 (Exception): Notice: Use of undefined constant php - assumed 'php' in /public_html/app/code/Ebizmarts/AutoResponder/view/adminhtml/templates/system/config/birthday/fieldset/hint.phtml on line 1`

**Possible solution**
I got this error after upgrading to MageMonkey 3.0.7 so I guess it's related ?

**Comment by vonwolfgraphics** [comment]
I'm getting the same error. Have you found a way to resolve this?

**Comment by SantiParagarino** [comment]
Hello,

Please check the commit referenced above. This fix will be available on next version.

Regards.
